# Docker container for DeepPATH demo workflow; make the parent Docker first!
FROM stevekm/deeppath

MAINTAINER Stephen M. Kelly

# clone the DeepPATH repo
RUN git clone https://github.com/stevekm/DeepPATH

# add in the demo files
